### ISSUE TITLE
Interactive & Dry run mode

### ISSUE THREAD

**Issue by maman** [hellowin/github-clear-merged-pull-requests#1]
Rather than directly deleting all repo, can you add a flag to:

1. Dry run: shows all merged branches, that will be deleted without actually deleting them.

2. Interactive delete: instead of automatically delete, show a prompt to user that shows the branch - and y/n prompt. This may not feasible for repo with many branches though.

**Comment by hellowin** [comment]
make sense, can be an optional though. this one I created is for deleting branch which are more than 2000 branches on my office though 😄 

can be good improvement I think. something like a `-y` flag for auto deletion.

**Comment by hellowin** [comment]
Enhanced https://github.com/hellowin/github-clear-merged-pull-requests/pull/2

For dry run, it's better to not implemented, since GitHub API must do lot request to get the list, it's better to keep the process based on GH API pagination.
